name: Deploy Node.js to Namecheap (Debug)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a 10-minute timeout for the entire job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Display public key for verification
        ssh-keygen -y -f ~/.ssh/id_rsa

    - name: Test SSH Connection
      env:
        HOST: ywambtnk@66.29.132.10
        PORT: 21098
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSWORD }}
      run: |
        sudo apt-get install sshpass -y
        export SSHPASS=$SSH_PASSPHRASE
        sshpass -e ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $PORT $HOST echo "SSH connection successful"

    - name: Deploy to Namecheap
      env:
        HOST: ywambtnk@66.29.132.10
        PORT: 21098
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSWORD }}
      run: |
        export SSHPASS=$SSH_PASSPHRASE
        sshpass -e ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $PORT $HOST << 'EOF'
          echo "Connected to server"
          cd /app || echo "Failed to change directory"
          echo "Current directory: $(pwd)"
          git pull origin main || echo "Git pull failed"
          echo "Deployment complete"
        EOF