name: Deploy Node.js to Namecheap

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Namecheap
      env:
        HOST: ywambtnk@66.29.132.10
        PORT: 21098
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Use sshpass to provide the passphrase
        sudo apt-get install sshpass -y
        export SSHPASS=$SSH_PASSPHRASE
        sshpass -e ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $PORT $HOST << 'EOF'
          cd /app
          git pull origin main
        EOF