name: Deploy Node.js to Namecheap

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run:  |
        eval "$(ssh-agent -s)"
        
        # Add SSH key to the agent
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null

        # Add SSH passphrase if required
        echo "${{ secrets.SSH_PASSWORD }}" | ssh-add -p
      # with:
        # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Namecheap
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no ywambtnk@66.29.132.10 -p 21098 << 'EOF'
          cd /app
          git pull origin main
        EOF
